# Imports

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import collections
from matplotlib import pyplot
import statistics
import datetime
from mpl_toolkits.axes_grid1 import make_axes_locatable

In [2]:
#!pip install geopandas
import geopandas as gpd

In [3]:
#import networkx as nx
#from networkx import readwrite

In [4]:
import warnings
warnings.filterwarnings("ignore")

# Import datasets

In [5]:
# the miners file 
# with calvert city in MISO
#df_miners = pd.read_excel('/Users/gianlucaguidi/Library/CloudStorage/GoogleDrive-g.guidi15@studenti.unipi.it/My Drive/BostonProject/BitData/btc-mining-proj/crypto_lookup_loc_summary_fulldates.xlsx')
#df_miners['start_date']

#with calvert city in TVA
df_miners = pd.read_excel('../data/input_private/crypto_loc_summary_calvertcity.xlsx')
df_miners#['start_date']


#df_miners = pd.read_csv('/Users/gianlucaguidi/Library/CloudStorage/GoogleDrive-g.guidi15@studenti.unipi.it/My Drive/BostonProject/BitData/btc-mining-proj/crypto_lookup_loc_summary_1.csv')
#df_miners['start_date']

,Unnamed: 0,ready,id,name,city,lat,long,company,mw,proposed_mw,...,Grid Region,annualMOER,annualMOERuptime,averageGridRegion,averageEmissions,averageEmissionsUptime,Unnamed: 20,eGRID BA,eGRID Average Emissions Rate,eGRID Marginal Emissions Rate
0,0,True,whinstone_us_rockdale_tx,Whinstone US,Rockdale,30.574978,-97.079562,Riot Digital,450,750.0,...,ERCOT_EASTTX,0.515331,0.512168,ERCOT,0.319476,0.312938,NaN,ERCO,0.371590,0.537636
1,1,True,genesis_pyote_tx,Genesis Digital,Pyote,31.597207,-103.250434,Genesis Digital Assets,135,300.0,...,ERCOT_WESTTX,0.490353,0.485901,ERCOT,0.319476,0.312938,NaN,ERCO,0.371590,0.537636
2,2,True,compute_north_upton_tx,Compute North,McCamey,31.254233,-102.243727,US Bitcoin,200,280.0,...,ERCOT_WESTTX,0.490353,0.485901,ERCOT,0.319476,0.312938,NaN,ERCO,0.371590,0.537636
3,3,True,bitdeer_rockdale_tx,BitDeer,Rockdale,30.564700,-97.069580,BitDeer,170,742.0,...,ERCOT_EASTTX,0.515331,0.512168,ERCOT,0.319476,0.312938,NaN,ERCO,0.371590,0.537636
4,4,True,core_scientific_calvert_city_ky,Calvert Data Center,Calvert City,37.050459,-88.397894,Core Scientific,150,150.0,...,TVA,0.630536,0.627032,MISO,0.447890,0.442029,NaN,MISO,0.519503,0.725851
5,5,True,massena_complex_massena_ny,Massena Complex,Massena,44.982191,-74.751944,Coinmint,150,435.0,...,NYISO_NORTH,0.357997,0.354729,NYISO,0.201799,0.200228,NaN,NYIS,0.213434,0.453081
6,6,True,core_scientific_dalton_green_dalton_ga,Dalton Green,Dalton,34.700218,-84.951086,Core Scientific,142,145.0,...,SOCO,0.533209,0.530889,SOCO,0.258038,0.253017,NaN,SOCO,0.406837,0.637718
7,7,True,atlas_power_williston_nd,Atlas Power,Williston,48.146950,-103.773862,Atlas Power,240,700.0,...,SPP_FORTPECK,0.529845,0.522196,SPP,0.388421,0.377177,NaN,SWPP,0.453368,0.791481
8,8,True,cipher_odessa_tx,Cipher Mining,Odessa,31.842005,-102.320156,Cipher Mining,207,205.0,...,ERCOT_WESTTX,0.490353,0.485901,ERCOT,0.319476,0.312938,NaN,ERCO,0.371590,0.537636
9,9,True,core_scientific_cherokee_county_facility_marbl...,Core Scientific Cherokee County facility 1,Marble,35.186752,-83.916565,Core Scientific,35,35.0,...,TVA,0.533209,0.530889,TVA,0.258038,0.253017,NaN,TVA,0.296180,0.672122
10,10,True,core_scientific_cherokee_county_facility_marbl...,Core Scientific Cherokee County facility 2,Marble,35.186752,-83.916565,Core Scientific,69,69.0,...,DUK,0.533209,0.530889,DUK,0.258038,0.253017,NaN,DUK,0.242102,0.605986
11,11,True,argo_afton_tx,Argo,Afton,33.776470,-100.868940,Galaxy Digital,100,200.0,...,ERCOT_NORTHCENTRAL,0.485807,0.481218,ERCOT,0.319476,0.312938,NaN,ERCO,0.371590,0.537636
12,12,True,poolin__pecos_tx,Poolin,Pecos,31.452287,-103.093909,Poolin,100,600.0,...,ERCOT_WESTTX,0.490353,0.485901,ERCOT,0.319476,0.312938,NaN,ERCO,0.371590,0.537636
13,13,True,compute_north_buffalo_county_facility_kearney_ne,Compute North Buffalo County facility,Kearney,40.725943,-99.038105,US Bitcoin,100,100.0,...,SPP_WESTNE,0.471816,0.461188,SPP,0.388421,0.377177,NaN,SWPP,0.453368,0.791481
14,14,True,core_scientific_grand_forks_county_facility_gr...,Core Scientific Grand Forks County facility,Grand Forks,47.909478,-97.111491,Core Scientific,100,100.0,...,MISO_N_DAKOTA,0.497500,0.488406,MISO,0.388421,0.377177,NaN,MISO,0.519503,0.725851
15,15,True,merkle_standard_pend_oreille_county_facility_u...,Merkle Standard Pend Oreille County facility,Usk,48.288454,-117.271422,Merkle Standard,100,500.0,...,AVA,0.421722,0.413596,AVA,0.102252,0.097243,NaN,AVA,0.118421,0.338352
16,16,True,merkle_standard_south_carolina,NaN,Spartanburg county,34.857146,-82.008715,Merkle Standard,40,NaN,...,DUK,0.599026,0.596464,DUK,0.262479,0.256932,NaN,DUK,0.242102,0.605986
17,17,True,applied_blockchain_jamestown_nd,Applied Blockchain Stutsman County facility,Jamestown,47.026657,-98.680507,Applied Blockchain,92,200.0,...,MISO_N_DAKOTA,0.624011,0.620426,MISO,0.447890,0.442029,NaN,MISO,0.519503,0.725851
18,18,True,mawson_infrastructure_group_midland_pa,Mawson Infrastructure Group,Midland,40.635577,-80.459617,Mawson Infrastructure Group,50,100.0,...,PJM_EASTERN_OH,0.568853,0.550298,PJM,0.338641,0.312979,NaN,PJM,0.370972,0.701546
19,19,True,core_scientific_pecos_tx,Core Scientific,Pecos,31.532678,-103.803412,Core Scientific,140,200.0,...,ERCOT_WESTTX,0.490353,0.485901,ERCOT,0.319476,0.312938,NaN,ERCO,0.371590,0.537636
20,20,True,sangha_systems_hennepin_il,Sangha Systems 82 River North,Hennepin,41.266710,-89.321760,BIT Intelligence LLC,82,82.0,...,MISO_SPRINGFIELD,0.630550,0.627054,MISO,0.447890,0.442029,NaN,MISO,0.519503,0.725851
21,21,True,cleanspark_sandersville_ga,Mawson Infrastructure Group Washington County ...,Sandersville,33.001648,-82.832774,CleanSpark,72,230.0,...,SOCO,0.529433,0.524407,SOCO,0.383859,0.379267,NaN,SOCO,0.406837,0.637718
22,22,True,digihost_tonawanda_ny,Digihost,North Tonawanda,43.048628,-78.852104,Digihost,46,102.0,...,NYISO_WEST,0.396240,0.390479,NYISO,0.201799,0.198234,NaN,NYIS,0.213434,0.453081
23,23,True,atlas_power_butte_mt,Atlas Power,Butte,45.929368,-112.520712,Atlas Power,75,128.0,...,MPCO,0.538723,0.532477,MPCO,0.611348,0.604445,NaN,NWMT,0.720065,0.986385
24,24,True,core_scientific_denton_tx,Core Scientific,Denton,33.212915,-97.210001,Core Scientific,125,200.0,...,ERCOT_NORTHCENTRAL,0.485807,0.481218,ERCOT,0.319476,0.312938,NaN,ERCO,0.371590,0.537636
25,25,True,terawulf_lake_mariner_somerset_ny,TeraWulf Lake Mariner,Somerset,43.359859,-78.601594,Terawulf,60,500.0,...,NYISO_WEST,0.396240,0.373052,NYISO,0.201799,0.188936,NaN,NYIS,0.213434,0.453081
26,26,True,bitdeer_knoxville_tn,Bitdeer,Knoxville,35.941551,-83.835483,Bitdeer,60,86.0,...,TVA,0.533209,0.530889,TVA,0.258038,0.253017,NaN,TVA,0.296180,0.672122
27,27,True,aboutbit_sullivan_county_facility_merom_in,AboutBit Sullivan County facility,Sullivan,39.057140,-87.509080,AboutBit,57,115.0,...,MISO_INDIANAPOLIS,0.630536,0.627032,MISO,0.447890,0.442029,NaN,MISO,0.519503,0.725851
28,28,True,viking_data_centers_oh,NaN,Akron,41.050186,-81.473951,Viking,150,150.0,...,PJM_EASTERN_OH,0.568853,0.565125,PJM,0.338641,0.333913,NaN,PJM,0.370972,0.701546
29,29,True,greenidge_generation_dresden_ny,Greenidge Generation,Dresden,42.679278,-76.948549,Greenidge Generation LLC,55,55.0,...,NYISO_CENTRAL,0.395653,0.389839,NYISO,0.201799,0.198234,NaN,NYIS,0.213434,0.453081
30,30,True,core_scientific_dalton_brown_dalton_ga,Dalton Brown,Dalton,34.713050,-84.951334,Core Scientific,53,50.0,...,SOCO,0.533209,0.530889,SOCO,0.258038,0.253017,NaN,SOCO,0.406837,0.637718
31,31,True,cleanspark_college_park_ga,NaN,College Park,33.654140,-84.450160,CleanSpark,38,46.0,...,SOCO,0.529433,0.524407,SOCO,0.383859,0.379267,NaN,SOCO,0.406837,0.637718
32,32,True,stronghold_digital_mining_kennerdell_pa,Stronghold Digital Mining,Kennerdell,41.271832,-79.814233,Stronghold Digital Mining,41,85.0,...,PJM_NJ,0.567875,0.564095,PJM,0.338641,0.333913,NaN,PJM,0.370972,0.701546
33,33,True,stronghold_digital_mining_nesquehoning_pa,Stronghold Digital Mining,Nesquehoning,40.852814,-75.876006,Stronghold Digital Mining,41,80.0,...,PJM_NJ,0.567875,0.564095,PJM,0.338641,0.333913,NaN,PJM,0.370972,0.701546
34,34,True,rhodium_temple_tx,NaN,Temple,31.057724,-97.298302,Rhodium Enterprises,185,NaN,...,ERCOT_AUSTIN,0.484743,0.480113,ERCOT,0.319476,0.312938,NaN,ERCO,0.371590,0.537636

In [6]:
df_miners.id

0                              whinstone_us_rockdale_tx
1                                      genesis_pyote_tx
2                                compute_north_upton_tx
3                                   bitdeer_rockdale_tx
4                       core_scientific_calvert_city_ky
5                            massena_complex_massena_ny
6                core_scientific_dalton_green_dalton_ga
7                              atlas_power_williston_nd
8                                      cipher_odessa_tx
9     core_scientific_cherokee_county_facility_marbl...
10    core_scientific_cherokee_county_facility_marbl...
11                                        argo_afton_tx
12                                     poolin__pecos_tx
13     compute_north_buffalo_county_facility_kearney_ne
14    core_scientific_grand_forks_county_facility_gr...
15    merkle_standard_pend_oreille_county_facility_u...
16                       merkle_standard_south_carolina
17                      applied_blockchain_jamestown_nd
18               mawson_infrastructure_group_midland_pa
19                             core_scientific_pecos_tx
20                           sangha_systems_hennepin_il
21                           cleanspark_sandersville_ga
22                                digihost_tonawanda_ny
23                                 atlas_power_butte_mt
24                            core_scientific_denton_tx
25                    terawulf_lake_mariner_somerset_ny
26                                 bitdeer_knoxville_tn
27           aboutbit_sullivan_county_facility_merom_in
28                               viking_data_centers_oh
29                      greenidge_generation_dresden_ny
30               core_scientific_dalton_brown_dalton_ga
31                           cleanspark_college_park_ga
32              stronghold_digital_mining_kennerdell_pa
33            stronghold_digital_mining_nesquehoning_pa
34                                    rhodium_temple_tx
Name: id, dtype: object

In [7]:
df_miners[df_miners.id == 'whinstone_us_rockdale_tx']

,Unnamed: 0,ready,id,name,city,lat,long,company,mw,proposed_mw,...,Grid Region,annualMOER,annualMOERuptime,averageGridRegion,averageEmissions,averageEmissionsUptime,Unnamed: 20,eGRID BA,eGRID Average Emissions Rate,eGRID Marginal Emissions Rate
0,0,True,whinstone_us_rockdale_tx,Whinstone US,Rockdale,30.574978,-97.079562,Riot Digital,450,750.0,...,ERCOT_EASTTX,0.515331,0.512168,ERCOT,0.319476,0.312938,NaN,ERCO,0.37159,0.537636

In [8]:
df_miners[df_miners['Grid Region']	== 'SOCO']

,Unnamed: 0,ready,id,name,city,lat,long,company,mw,proposed_mw,...,Grid Region,annualMOER,annualMOERuptime,averageGridRegion,averageEmissions,averageEmissionsUptime,Unnamed: 20,eGRID BA,eGRID Average Emissions Rate,eGRID Marginal Emissions Rate
6,6,True,core_scientific_dalton_green_dalton_ga,Dalton Green,Dalton,34.700218,-84.951086,Core Scientific,142,145.0,...,SOCO,0.533209,0.530889,SOCO,0.258038,0.253017,NaN,SOCO,0.406837,0.637718
21,21,True,cleanspark_sandersville_ga,Mawson Infrastructure Group Washington County ...,Sandersville,33.001648,-82.832774,CleanSpark,72,230.0,...,SOCO,0.529433,0.524407,SOCO,0.383859,0.379267,NaN,SOCO,0.406837,0.637718
30,30,True,core_scientific_dalton_brown_dalton_ga,Dalton Brown,Dalton,34.713050,-84.951334,Core Scientific,53,50.0,...,SOCO,0.533209,0.530889,SOCO,0.258038,0.253017,NaN,SOCO,0.406837,0.637718
31,31,True,cleanspark_college_park_ga,NaN,College Park,33.654140,-84.450160,CleanSpark,38,46.0,...,SOCO,0.529433,0.524407,SOCO,0.383859,0.379267,NaN,SOCO,0.406837,0.637718

In [9]:
# the unit_rates file (power plants)

df_unit_rates = pd.read_csv('../data/input_private/condensed_unit_rates.csv')
df_unit_rates.pop('Unnamed: 0')
df_unit_rates

,plant_unit,month,nox_lbs_per_mwh,so2_lbs_per_mwh,co2_lbs_per_mwh,pm25_lbs_per_mwh,height,temp,diam,velocity,PlumeHeight,LAT,LON
0,3_1,1,0.985806,0.008655,1714.236001,0.102510,182.8800,422.038889,7.821168,8.558784,614.982220,31.006900,-88.010300
1,3_1,2,0.661901,0.007830,1551.306931,0.092693,182.8800,422.038889,7.821168,8.558784,614.982220,31.006900,-88.010300
2,3_1,3,1.041321,0.186222,1836.505381,0.110113,182.8800,422.038889,7.821168,8.558784,614.982220,31.006900,-88.010300
3,3_1,4,0.831544,0.054681,1646.441756,0.098525,182.8800,422.038889,7.821168,8.558784,614.982220,31.006900,-88.010300
4,3_1,5,0.962448,0.196107,1846.349086,0.110695,182.8800,422.038889,7.821168,8.558784,614.982220,31.006900,-88.010300
...,...,...,...,...,...,...,...,...,...,...,...,...,...
48683,70454_MAG2,8,0.777484,0.007065,1399.569292,0.097369,24.0792,869.261111,6.858000,35.661600,318.917196,34.339588,-82.819871
48684,70454_MAG2,9,0.851637,0.006936,1374.011672,0.095590,24.0792,869.261111,6.858000,35.661600,318.917196,34.339588,-82.819871
48685,70454_MAG2,10,0.859994,0.007007,1388.032424,0.096569,24.0792,869.261111,6.858000,35.661600,318.917196,34.339588,-82.819871
48686,70454_MAG2,11,0.929189,0.010025,1560.555031,0.106596,24.0792,869.261111,6.858000,35.661600,318.917196,34.339588,-82.819871
48687,70454_MAG2,12,0.735857,0.007323,1420.094528,0.098642,24.0792,869.261111,6.858000,35.661600,318.917196,34.339588,-82.819871

In [10]:
#example ERCOT_EASTTX
df_moers = pd.read_csv(f'../data/input_private/ERCOT_EASTTX_plant_mix.csv', parse_dates=["ts"])

In [11]:
(df_moers[df_moers.columns[1:]]< 0).sum().sum()

8298

In [12]:
#df_unit_rates = pd.read_csv('/Users/gianlucaguidi/Library/CloudStorage/GoogleDrive-g.guidi15@studenti.unipi.it/My Drive/BostonProject/BitData/btc-mining-proj/condensed_unit_rates.csv')
#df_unit_rates.pop('Unnamed: 0')
#df_unit_rates

# function

In [13]:
# run before function 
date = ['2018-01',
 '2018-02',
 '2018-03',
 '2018-04',
 '2018-05',
 '2018-06',
 '2018-07',
 '2018-08',
 '2018-09',
 '2018-10',
 '2018-11',
 '2018-12',
 '2019-01',
 '2019-02',
 '2019-03',
 '2019-04',
 '2019-05',
 '2019-06',
 '2019-07',
 '2019-08',
 '2019-09',
 '2019-10',
 '2019-11',
 '2019-12',
 '2020-01',
 '2020-02',
 '2020-03',
 '2020-04',
 '2020-05',
 '2020-06',
 '2020-07',
 '2020-08',
 '2020-09',
 '2020-10',
 '2020-11',
 '2020-12',
 '2021-01',
 '2021-02',
 '2021-03',
 '2021-04',
 '2021-05',
 '2021-06',
 '2021-07',
 '2021-08',
 '2021-09',
 '2021-10',
 '2021-11',
 '2021-12',
 '2022-01',
 '2022-02',
 '2022-03',
 '2022-04',
 '2022-05',
 '2022-06',
 '2022-07',
 '2022-08',
 '2022-09',
 '2022-10',
 '2022-11',
 '2022-12',
 '2023-01',
 '2023-02',
 '2023-03',
 '2023-04',
 '2023-05',
 '2023-06',
 '2023-07',
 '2023-08']

In [14]:
df_miners[['id','uptime']]

                                                   id  uptime
0                            whinstone_us_rockdale_tx    0.95
1                                    genesis_pyote_tx    0.95
2                              compute_north_upton_tx    0.95
3                                 bitdeer_rockdale_tx    0.95
4                     core_scientific_calvert_city_ky    0.95
5                          massena_complex_massena_ny    0.98
6              core_scientific_dalton_green_dalton_ga    0.95
7                            atlas_power_williston_nd    0.95
8                                    cipher_odessa_tx    0.95
9   core_scientific_cherokee_county_facility_marbl...    0.95
10  core_scientific_cherokee_county_facility_marbl...    0.95
11                                      argo_afton_tx    0.95
12                                   poolin__pecos_tx    0.95
13   compute_north_buffalo_county_facility_kearney_ne    0.95
14  core_scientific_grand_forks_county_facility_gr...    0.95
15  merkle_standard_pend_oreille_county_facility_u...    0.95
16                     merkle_standard_south_carolina    0.95
17                    applied_blockchain_jamestown_nd    0.95
18             mawson_infrastructure_group_midland_pa    0.63
19                           core_scientific_pecos_tx    0.95
20                         sangha_systems_hennepin_il    0.95
21                         cleanspark_sandersville_ga    0.95
22                              digihost_tonawanda_ny    0.95
23                               atlas_power_butte_mt    0.95
24                          core_scientific_denton_tx    0.95
25                  terawulf_lake_mariner_somerset_ny    0.77
26                               bitdeer_knoxville_tn    0.95
27         aboutbit_sullivan_county_facility_merom_in    0.95
28                             viking_data_centers_oh    0.95
29                    greenidge_generation_dresden_ny    0.95
30             core_scientific_dalton_brown_dalton_ga    0.95
31                         cleanspark_college_park_ga    0.95
32            stronghold_digital_mining_kennerdell_pa    0.95
33          stronghold_digital_mining_nesquehoning_pa    0.95
34                                  rhodium_temple_tx    0.95

In [15]:
def find_miner_emissions(miner, period=['daily', 'monthly'], wattime_data=[True, False]):
    
    #condition selecting the miner indicated
    condition = df_miners['id'] == miner
    #getting the area and moers for the grid region of the selected miner 
    area = df_miners[condition]['Grid Region'].item()
    
    #miner start date
    start_date = df_miners[condition]['start_date'].dt.to_period('M').item()
    
    df_moers = pd.read_csv(f'../data/input_private/{area}_plant_mix.csv')
    df_moers['Date'] = pd.to_datetime(df_moers[f'{df_moers.columns[0]}'])
    df_moers_num = df_moers.select_dtypes(include=[np.number])
    df_daily = df_moers_num.groupby(df_moers['Date'].dt.date).mean() #average per day to get the daily values
    df_monthly = df_moers_num.groupby(df_moers['Date'].dt.to_period('M')).mean() # Aggregate from daily to monthly marginal data
    n_plants = len(df_daily.columns) 
    
    df_unit_rates = pd.read_csv('../data/input_private/condensed_unit_rates.csv')
    df_unit_rates.pop('Unnamed: 0')

    # Miner MW power capacity
    mw_power_capacity = df_miners[condition]['mw'].item()
    #first term: power capacity per hour, times hours in a day, times day in a year (to find the MW demanded in a year at full capacity)
    #second term: uptime, that is the time that we consider the miner working at full capacity
    yearly_mw_demand = (mw_power_capacity*24*365) * df_miners[condition]['uptime'].item()
        
    daily_mw_demanded = yearly_mw_demand/365
    monthly_mw_demanded = yearly_mw_demand/12
    
    
    
    # DAILY

    if (period == 'daily'):
        
        #WITHOUT WATTIME DATA
        
        # Aggregate from hourly to daily marginal data
        df_daily1 = df_moers_num.groupby(df_moers['Date'].dt.date).mean() #average per day to get the daily values

        # build a MOER table without considering WATTIMe data (all power plants contribute equally)
        df_daily1[:] = np.where(df_daily[:] > -1 , 1/n_plants, df_daily[:])
        
        df_daily_times_miner1 = df_daily1.multiply(daily_mw_demanded, axis=1) #portion for the current miner supplied by each power plant
        
        df_daily_times_miner1['date'] = pd.to_datetime(df_daily_times_miner1.index)
        df_daily_times_miner1['month'] = pd.DatetimeIndex(df_daily_times_miner1['date']).month
        df_daily_times_miner1['year'] = pd.DatetimeIndex(df_daily_times_miner1['date']).year
        df_daily_times_miner1['day'] = pd.DatetimeIndex(df_daily_times_miner1['date']).day
        df_daily_times_miner1.set_index(['year','month','day'],inplace = True)
        df_daily_times_miner1.pop('date')
        
        transposed_df1 = df_daily_times_miner1.stack().reset_index()
        transposed_df1.rename(columns={"level_3": "plant_unit", 0:'marginalMW'}, inplace = True)
        df_merged1 = pd.merge(transposed_df1, df_unit_rates, right_on = ['plant_unit','month'], left_on = ['plant_unit','month'])
        df_merged1.drop_duplicates(inplace=True)
    
        #WITH WATTIME DATA
        
        #make negative moers = 0
        df_daily[df_daily < 0] = 0
        
        mw_demanded_per_plant_per_day2  = df_daily.multiply(daily_mw_demanded, axis=1)
        mw_demanded_per_plant_per_day2['date'] = pd.to_datetime(mw_demanded_per_plant_per_day2.index)
        mw_demanded_per_plant_per_day2['month'] = pd.DatetimeIndex(mw_demanded_per_plant_per_day2['date']).month
        mw_demanded_per_plant_per_day2['year'] = pd.DatetimeIndex(mw_demanded_per_plant_per_day2['date']).year
        mw_demanded_per_plant_per_day2['day'] = pd.DatetimeIndex(mw_demanded_per_plant_per_day2['date']).day
        mw_demanded_per_plant_per_day2.set_index(['year','month','day'],inplace = True)
        mw_demanded_per_plant_per_day2.pop('date')
        
        transposed_df2 = mw_demanded_per_plant_per_day2.stack().reset_index()
        transposed_df2.rename(columns={"level_3": "plant_unit", 0:'marginalMW'}, inplace = True)
        
        df_merged2 = pd.merge(transposed_df2, df_merged1, right_on = ['plant_unit','year','month','day'], left_on = ['plant_unit','year','month','day'], how='outer')
        df_merged2.rename(columns={"marginalMW_x": "marginalMW_wattime", 'marginalMW_y':'marginalMW_NO_wattime'}, inplace = True)
        #compute emissions
        df_merged2['co2_lbs_wattime'] = df_merged2['marginalMW_wattime'] * df_merged2['co2_lbs_per_mwh']
        df_merged2['nox_lbs_wattime'] = df_merged2['marginalMW_wattime'] * df_merged2['nox_lbs_per_mwh']
        df_merged2['so2_lbs_wattime'] = df_merged2['marginalMW_wattime'] * df_merged2['so2_lbs_per_mwh']  
        df_merged2['pm25_lbs_wattime'] = df_merged2['marginalMW_wattime'] * df_merged2['pm25_lbs_per_mwh']
    
        df_merged2['co2_lbs_NO_wattime'] = df_merged2['marginalMW_NO_wattime'] * df_merged2['co2_lbs_per_mwh']
        df_merged2['nox_lbs_NO_wattime'] = df_merged2['marginalMW_NO_wattime'] * df_merged2['nox_lbs_per_mwh']
        df_merged2['so2_lbs_NO_wattime'] = df_merged2['marginalMW_NO_wattime'] * df_merged2['so2_lbs_per_mwh']
        df_merged2['pm25_lbs_NO_wattime'] = df_merged2['marginalMW_NO_wattime'] * df_merged2['pm25_lbs_per_mwh']
        
        df_merged2.drop_duplicates(inplace=True)
        df_merged2['miner'] = miner

        df_merged2_light = df_merged2[['year','month','day','miner','plant_unit','height','temp','diam','velocity','PlumeHeight','LAT','LON','marginalMW_wattime','marginalMW_NO_wattime','co2_lbs_wattime','nox_lbs_wattime','so2_lbs_wattime', 'pm25_lbs_wattime','co2_lbs_NO_wattime','nox_lbs_NO_wattime','so2_lbs_NO_wattime', 'pm25_lbs_NO_wattime']]
        
        if wattime_data == False:
            df_merged2_light = df_merged2[['year','month','day','miner','plant_unit','height','temp','diam','velocity','PlumeHeight','LAT','LON','marginalMW_NO_wattime','co2_lbs_NO_wattime','nox_lbs_NO_wattime','so2_lbs_NO_wattime', 'pm25_lbs_NO_wattime']]
            return df_merged2_light 
        if wattime_data == True:
            df_merged2_light = df_merged2[['year','month','day','miner','plant_unit','height','temp','diam','velocity','PlumeHeight','LAT','LON','marginalMW_wattime','co2_lbs_wattime','nox_lbs_wattime','so2_lbs_wattime', 'pm25_lbs_wattime']]
            return df_merged2_light
        else:
            return df_merged2_light
        
        
        
    # MONTHLY
    if period == 'monthly':
        
        
        #WITHOUT WATTIME DATA
        
        mw_demanded_per_plant_per_month1 = monthly_mw_demanded / n_plants
        # Aggregate from hourly to daily marginal data
        df_monthly1 = df_moers_num.groupby(df_moers['Date'].dt.to_period('M')).mean() # Aggregate from daily to monthly marginal data

        # build a MOER table without considering WATTIMe data (all power plants contribute equally)
        df_monthly1[:] = np.where(df_monthly[:] > -1 , 1/n_plants, df_monthly[:])
        
        df_monthly_times_miner1 = df_monthly1.multiply(monthly_mw_demanded, axis=1) #portion for the current miner supplied by each power plant
        
        #i create a moers df starting 2018
        cols = list(df_monthly_times_miner1.columns)
        
        df_monthly_times_miner2 = pd.DataFrame(columns=cols, index=date)
        df_monthly_times_miner2.index = pd.to_datetime(df_monthly_times_miner2.index).to_period('M')
        df_monthly_times_miner2 = df_monthly_times_miner2.fillna(df_monthly_times_miner1.iat[0, 0]) # select one value from the df_monthly_times_miner1 table (theyre all the same!)
        
        
        
        #start date (select only month in which the miner was operating)
        df_monthly_times_miner2 = df_monthly_times_miner2.loc[(df_monthly_times_miner2.index > start_date)] 
        
        
        df_monthly_times_miner2['month'] = df_monthly_times_miner2.index.month
        df_monthly_times_miner2['year'] = df_monthly_times_miner2.index.year
        df_monthly_times_miner2.set_index(['year','month'],inplace = True)
        
        transposed_df = df_monthly_times_miner2.stack().reset_index()
        transposed_df.rename(columns={"level_2": "plant_unit", 0:'marginalMW'}, inplace = True)
        df_merged = pd.merge(transposed_df, df_unit_rates, right_on = ['plant_unit','month'], left_on = ['plant_unit','month'])
        
    
        #WITH WATTIME DATA
        df_monthly[df_monthly < 0] = 0

        
        mw_demanded_per_plant_per_month2  = df_monthly.multiply(monthly_mw_demanded, axis=1)
        
        #start date
        mw_demanded_per_plant_per_month2 = mw_demanded_per_plant_per_month2.loc[(mw_demanded_per_plant_per_month2.index > start_date)]
        
        mw_demanded_per_plant_per_month2['month'] = mw_demanded_per_plant_per_month2.index.month
        mw_demanded_per_plant_per_month2['year'] = mw_demanded_per_plant_per_month2.index.year
        mw_demanded_per_plant_per_month2.set_index(['year','month'],inplace = True)
        
        transposed_df = mw_demanded_per_plant_per_month2.stack().reset_index()
        transposed_df.rename(columns={"level_2": "plant_unit", 0:'marginalMW'}, inplace = True)
        df_merged2 = pd.merge(transposed_df, df_merged, right_on = ['plant_unit','year','month'], left_on = ['plant_unit','year','month'], how='outer')
        df_merged2.rename(columns={"marginalMW_x": "marginalMW_wattime", 'marginalMW_y':'marginalMW_NO_wattime'}, inplace = True)
        #compute emissions
        df_merged2['co2_lbs_wattime'] = df_merged2['marginalMW_wattime'] * df_merged2['co2_lbs_per_mwh']
        df_merged2['nox_lbs_wattime'] = df_merged2['marginalMW_wattime'] * df_merged2['nox_lbs_per_mwh']
        df_merged2['so2_lbs_wattime'] = df_merged2['marginalMW_wattime'] * df_merged2['so2_lbs_per_mwh']  
        df_merged2['pm25_lbs_wattime'] = df_merged2['marginalMW_wattime'] * df_merged2['pm25_lbs_per_mwh']
    
        df_merged2['co2_lbs_NO_wattime'] = df_merged2['marginalMW_NO_wattime'] * df_merged2['co2_lbs_per_mwh']
        df_merged2['nox_lbs_NO_wattime'] = df_merged2['marginalMW_NO_wattime'] * df_merged2['nox_lbs_per_mwh']
        df_merged2['so2_lbs_NO_wattime'] = df_merged2['marginalMW_NO_wattime'] * df_merged2['so2_lbs_per_mwh']
        df_merged2['pm25_lbs_NO_wattime'] = df_merged2['marginalMW_NO_wattime'] * df_merged2['pm25_lbs_per_mwh']
        df_merged2.drop_duplicates(inplace=True)
        df_merged2['miner'] = miner
        df_merged2_light = df_merged2[['year','month','miner','plant_unit','LAT','LON','marginalMW_wattime','marginalMW_NO_wattime','co2_lbs_wattime','nox_lbs_wattime','so2_lbs_wattime', 'pm25_lbs_wattime','co2_lbs_NO_wattime','nox_lbs_NO_wattime','so2_lbs_NO_wattime', 'pm25_lbs_NO_wattime']]
        
        if wattime_data == False:
            df_merged2_light = df_merged2[['year','month','miner','plant_unit','LAT','LON','marginalMW_NO_wattime','co2_lbs_NO_wattime','nox_lbs_NO_wattime','so2_lbs_NO_wattime', 'pm25_lbs_NO_wattime']]
            return df_merged2_light 
        if wattime_data == True:
            df_merged2_light = df_merged2[['year','month','miner','plant_unit','LAT','LON','marginalMW_wattime','co2_lbs_wattime','nox_lbs_wattime','so2_lbs_wattime', 'pm25_lbs_wattime']]
            return df_merged2_light
        else:
            return df_merged2_light
        #df_merged2_light.to_csv(f'/Users/gianlucaguidi/Library/CloudStorage/GoogleDrive-g.guidi15@studenti.unipi.it/My Drive/BostonProject/{miner}_daily_emissions.csv')

In [16]:
find_miner_emissions(miner = 'whinstone_us_rockdale_tx', period= 'daily')#['marginalMW_NO_wattime'].sum()

,year,month,day,miner,plant_unit,height,temp,diam,velocity,PlumeHeight,...,marginalMW_wattime,marginalMW_NO_wattime,co2_lbs_wattime,nox_lbs_wattime,so2_lbs_wattime,pm25_lbs_wattime,co2_lbs_NO_wattime,nox_lbs_NO_wattime,so2_lbs_NO_wattime,pm25_lbs_NO_wattime
0,2020,1,1,whinstone_us_rockdale_tx,10298_CG801,28.956,437.038889,4.4196,22.95144,172.812248,...,1.283535,34.779661,2029.516511,0.336099,0.0,0.066190,54993.339471,9.107193,0.0,1.793546
1,2020,1,2,whinstone_us_rockdale_tx,10298_CG801,28.956,437.038889,4.4196,22.95144,172.812248,...,1.592955,34.779661,2518.768867,0.417122,0.0,0.082147,54993.339471,9.107193,0.0,1.793546
2,2020,1,3,whinstone_us_rockdale_tx,10298_CG801,28.956,437.038889,4.4196,22.95144,172.812248,...,1.355509,34.779661,2143.321090,0.354946,0.0,0.069902,54993.339471,9.107193,0.0,1.793546
3,2020,1,4,whinstone_us_rockdale_tx,10298_CG801,28.956,437.038889,4.4196,22.95144,172.812248,...,2.987301,34.779661,4723.498106,0.782237,0.0,0.154052,54993.339471,9.107193,0.0,1.793546
4,2020,1,5,whinstone_us_rockdale_tx,10298_CG801,28.956,437.038889,4.4196,22.95144,172.812248,...,2.239644,34.779661,3541.308087,0.586460,0.0,0.115496,54993.339471,9.107193,0.0,1.793546
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
388805,2023,8,6,whinstone_us_rockdale_tx,8063_CT4,18.288,808.705556,6.0960,26.45664,199.404326,...,4.715289,34.779661,6653.297324,38.963693,0.0,0.718297,49074.286046,287.393655,0.0,5.298109
388806,2023,8,7,whinstone_us_rockdale_tx,8063_CT4,18.288,808.705556,6.0960,26.45664,199.404326,...,12.270614,34.779661,17313.902039,101.395374,0.0,1.869226,49074.286046,287.393655,0.0,5.298109
388807,2023,8,8,whinstone_us_rockdale_tx,8063_CT4,18.288,808.705556,6.0960,26.45664,199.404326,...,8.969146,34.779661,12655.512655,74.114457,0.0,1.366302,49074.286046,287.393655,0.0,5.298109
388808,2023,8,9,whinstone_us_rockdale_tx,8063_CT4,18.288,808.705556,6.0960,26.45664,199.404326,...,15.153075,34.779661,21381.068604,125.213915,0.0,2.308322,49074.286046,287.393655,0.0,5.298109
388809,2023,8,10,whinstone_us_rockdale_tx,8063_CT4,18.288,808.705556,6.0960,26.45664,199.404326,...,72.760149,34.779661,102664.955666,601.236600,0.0,11.083812,49074.286046,287.393655,0.0,5.298109

In [16]:
find_miner_emissions(miner = 'whinstone_us_rockdale_tx', period = 'monthly', wattime_data = True)

,year,month,miner,plant_unit,LAT,LON,marginalMW_wattime,co2_lbs_wattime,nox_lbs_wattime,so2_lbs_wattime,pm25_lbs_wattime
0,2019,2,whinstone_us_rockdale_tx,10298_CG801,29.622500,-95.045800,NaN,NaN,NaN,NaN,NaN
1,2019,3,whinstone_us_rockdale_tx,10298_CG801,29.622500,-95.045800,NaN,NaN,NaN,NaN,NaN
2,2019,4,whinstone_us_rockdale_tx,10298_CG801,29.622500,-95.045800,NaN,NaN,NaN,NaN,NaN
3,2019,5,whinstone_us_rockdale_tx,10298_CG801,29.622500,-95.045800,NaN,NaN,NaN,NaN,NaN
4,2019,6,whinstone_us_rockdale_tx,10298_CG801,29.622500,-95.045800,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
16033,2023,4,whinstone_us_rockdale_tx,8063_CT4,32.403056,-97.700556,313.810291,363778.820394,2173.551911,0.0,39.178294
16034,2023,5,whinstone_us_rockdale_tx,8063_CT4,32.403056,-97.700556,261.364692,299217.449143,1746.065227,0.0,32.163510
16035,2023,6,whinstone_us_rockdale_tx,8063_CT4,32.403056,-97.700556,54.996688,83009.582936,485.680425,0.0,8.954120
16036,2023,7,whinstone_us_rockdale_tx,8063_CT4,32.403056,-97.700556,101.002731,134058.337128,785.783525,0.0,14.480991
16037,2023,8,whinstone_us_rockdale_tx,8063_CT4,32.403056,-97.700556,270.696277,381953.881366,2236.835845,0.0,41.236126

# analysis

In [17]:
len(df_miners.id.unique())

35

In [18]:
df_complete = []

for miner in df_miners.id.unique():
    print(miner)
    df = find_miner_emissions(miner=miner, period='monthly')
    df_complete.append(df)

# Concatenate all the dataframes in the list
df_complete = pd.concat(df_complete, ignore_index=True)

whinstone_us_rockdale_tx
genesis_pyote_tx
compute_north_upton_tx
bitdeer_rockdale_tx
core_scientific_calvert_city_ky
massena_complex_massena_ny
core_scientific_dalton_green_dalton_ga
atlas_power_williston_nd
cipher_odessa_tx
core_scientific_cherokee_county_facility_marble_nc_1
core_scientific_cherokee_county_facility_marble_nc_2
argo_afton_tx
poolin__pecos_tx
compute_north_buffalo_county_facility_kearney_ne
core_scientific_grand_forks_county_facility_grand_forks_nd
merkle_standard_pend_oreille_county_facility_usk_wa
merkle_standard_south_carolina
applied_blockchain_jamestown_nd
mawson_infrastructure_group_midland_pa
core_scientific_pecos_tx
sangha_systems_hennepin_il
cleanspark_sandersville_ga
digihost_tonawanda_ny
atlas_power_butte_mt
core_scientific_denton_tx
terawulf_lake_mariner_somerset_ny
bitdeer_knoxville_tn
aboutbit_sullivan_county_facility_merom_in
viking_data_centers_oh
greenidge_generation_dresden_ny
core_scientific_dalton_brown_dalton_ga
cleanspark_college_park_ga
stronghold_digital_mining_kennerdell_pa
stronghold_digital_mining_nesquehoning_pa
rhodium_temple_tx

In [19]:
#len(df_complete.groupby(['miner','plant_unit','LAT','LON','year','month']).sum().reset_index().miner.unique())

#print(df_complete[(df_complete[df_complete.marginalMW_wattime] < 0).all(axis=1)])#| (df[df.columns] <= 0).all(axis=1)])
df_complete

,year,month,miner,plant_unit,LAT,LON,marginalMW_wattime,marginalMW_NO_wattime,co2_lbs_wattime,nox_lbs_wattime,so2_lbs_wattime,pm25_lbs_wattime,co2_lbs_NO_wattime,nox_lbs_NO_wattime,so2_lbs_NO_wattime,pm25_lbs_NO_wattime
0,2019,2,whinstone_us_rockdale_tx,10298_CG801,29.622500,-95.045800,NaN,1057.881356,NaN,NaN,NaN,NaN,1.652695e+06,223.336059,0.0,53.306252
1,2019,3,whinstone_us_rockdale_tx,10298_CG801,29.622500,-95.045800,NaN,1057.881356,NaN,NaN,NaN,NaN,1.717854e+06,252.723027,0.0,55.183281
2,2019,4,whinstone_us_rockdale_tx,10298_CG801,29.622500,-95.045800,NaN,1057.881356,NaN,NaN,NaN,NaN,1.743636e+06,264.697816,0.0,55.403020
3,2019,5,whinstone_us_rockdale_tx,10298_CG801,29.622500,-95.045800,NaN,1057.881356,NaN,NaN,NaN,NaN,1.706724e+06,258.846181,0.0,55.023591
4,2019,6,whinstone_us_rockdale_tx,10298_CG801,29.622500,-95.045800,NaN,1057.881356,NaN,NaN,NaN,NaN,1.669530e+06,260.697501,0.0,53.933640
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212681,2023,4,rhodium_temple_tx,8063_CT4,32.403056,-97.700556,127.849994,434.906780,148207.758416,885.530543,0.0,15.961697,5.041577e+05,3012.305485,0.0,54.296835
212682,2023,5,rhodium_temple_tx,8063_CT4,32.403056,-97.700556,107.449929,434.906780,123011.617981,717.826816,0.0,13.222776,4.978932e+05,2905.425363,0.0,53.519580
212683,2023,6,rhodium_temple_tx,8063_CT4,32.403056,-97.700556,22.609749,434.906780,34126.161874,199.668619,0.0,3.681138,6.564292e+05,3840.698757,0.0,70.808037
212684,2023,7,rhodium_temple_tx,8063_CT4,32.403056,-97.700556,41.523345,434.906780,55112.871930,323.044338,0.0,5.953296,5.772406e+05,3383.498446,0.0,62.353573
212685,2023,8,rhodium_temple_tx,8063_CT4,32.403056,-97.700556,111.286247,434.906780,157025.484562,919.588070,0.0,16.952629,6.136558e+05,3593.751216,0.0,66.250895

In [20]:
df_complete = df_complete.drop_duplicates()
df_complete[df_complete.miner == 'core_scientific_calvert_city_ky']

,year,month,miner,plant_unit,LAT,LON,marginalMW_wattime,marginalMW_NO_wattime,co2_lbs_wattime,nox_lbs_wattime,so2_lbs_wattime,pm25_lbs_wattime,co2_lbs_NO_wattime,nox_lbs_NO_wattime,so2_lbs_NO_wattime,pm25_lbs_NO_wattime
42106,2019,6,core_scientific_calvert_city_ky,1378_PCC1,37.2608,-86.9783,NaN,1195.689655,NaN,NaN,NaN,NaN,9.507581e+05,268.057928,4.799706,45.727681
42107,2019,7,core_scientific_calvert_city_ky,1378_PCC1,37.2608,-86.9783,NaN,1195.689655,NaN,NaN,NaN,NaN,9.541027e+05,266.175727,4.816527,45.888622
42108,2019,8,core_scientific_calvert_city_ky,1378_PCC1,37.2608,-86.9783,NaN,1195.689655,NaN,NaN,NaN,NaN,9.566904e+05,319.867489,4.829634,46.012939
42109,2019,9,core_scientific_calvert_city_ky,1378_PCC1,37.2608,-86.9783,NaN,1195.689655,NaN,NaN,NaN,NaN,9.488514e+05,247.436451,4.789977,45.635817
42110,2019,10,core_scientific_calvert_city_ky,1378_PCC1,37.2608,-86.9783,NaN,1195.689655,NaN,NaN,NaN,NaN,9.502942e+05,280.851820,4.797331,45.705213
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46538,2023,4,core_scientific_calvert_city_ky,7845_LCT9,35.6578,-89.3964,0.000000,1195.689655,0.000000,0.000000,0.000000,0.000000,1.473113e+06,646.149152,151.006761,83.691509
46539,2023,5,core_scientific_calvert_city_ky,7845_LCT9,35.6578,-89.3964,0.000000,1195.689655,0.000000,0.000000,0.000000,0.000000,1.620673e+06,411.580262,12.844001,100.948756
46540,2023,6,core_scientific_calvert_city_ky,7845_LCT9,35.6578,-89.3964,86.224073,1195.689655,118049.072564,27.135107,0.992327,7.349605,1.637014e+06,376.288959,13.760840,101.918714
46541,2023,7,core_scientific_calvert_city_ky,7845_LCT9,35.6578,-89.3964,283.418033,1195.689655,393501.520448,82.679309,2.270226,24.562511,1.660112e+06,348.809120,9.577675,103.624813
46542,2023,8,core_scientific_calvert_city_ky,7845_LCT9,35.6578,-89.3964,96.992674,1195.689655,134122.481370,30.216463,0.677153,8.376249,1.653412e+06,372.497327,8.347685,103.259286

In [21]:
(df_complete.miner.unique())#.groupby(['plant_unit','LAT','LON','year','month']).sum().reset_index()

array(['whinstone_us_rockdale_tx', 'genesis_pyote_tx',
       'compute_north_upton_tx', 'bitdeer_rockdale_tx',
       'core_scientific_calvert_city_ky', 'massena_complex_massena_ny',
       'core_scientific_dalton_green_dalton_ga',
       'atlas_power_williston_nd', 'cipher_odessa_tx',
       'core_scientific_cherokee_county_facility_marble_nc_1',
       'core_scientific_cherokee_county_facility_marble_nc_2',
       'argo_afton_tx', 'poolin__pecos_tx',
       'compute_north_buffalo_county_facility_kearney_ne',
       'core_scientific_grand_forks_county_facility_grand_forks_nd',
       'merkle_standard_pend_oreille_county_facility_usk_wa',
       'merkle_standard_south_carolina',
       'applied_blockchain_jamestown_nd',
       'mawson_infrastructure_group_midland_pa',
       'core_scientific_pecos_tx', 'sangha_systems_hennepin_il',
       'cleanspark_sandersville_ga', 'digihost_tonawanda_ny',
       'atlas_power_butte_mt', 'core_scientific_denton_tx',
       'terawulf_lake_mariner_somerset_ny', 'bitdeer_knoxville_tn',
       'aboutbit_sullivan_county_facility_merom_in',
       'viking_data_centers_oh', 'greenidge_generation_dresden_ny',
       'core_scientific_dalton_brown_dalton_ga',
       'cleanspark_college_park_ga',
       'stronghold_digital_mining_kennerdell_pa',
       'stronghold_digital_mining_nesquehoning_pa', 'rhodium_temple_tx'],
      dtype=object)

# From august 22 to july 23

In [22]:
df_complete

,year,month,miner,plant_unit,LAT,LON,marginalMW_wattime,marginalMW_NO_wattime,co2_lbs_wattime,nox_lbs_wattime,so2_lbs_wattime,pm25_lbs_wattime,co2_lbs_NO_wattime,nox_lbs_NO_wattime,so2_lbs_NO_wattime,pm25_lbs_NO_wattime
0,2019,2,whinstone_us_rockdale_tx,10298_CG801,29.622500,-95.045800,NaN,1057.881356,NaN,NaN,NaN,NaN,1.652695e+06,223.336059,0.0,53.306252
1,2019,3,whinstone_us_rockdale_tx,10298_CG801,29.622500,-95.045800,NaN,1057.881356,NaN,NaN,NaN,NaN,1.717854e+06,252.723027,0.0,55.183281
2,2019,4,whinstone_us_rockdale_tx,10298_CG801,29.622500,-95.045800,NaN,1057.881356,NaN,NaN,NaN,NaN,1.743636e+06,264.697816,0.0,55.403020
3,2019,5,whinstone_us_rockdale_tx,10298_CG801,29.622500,-95.045800,NaN,1057.881356,NaN,NaN,NaN,NaN,1.706724e+06,258.846181,0.0,55.023591
4,2019,6,whinstone_us_rockdale_tx,10298_CG801,29.622500,-95.045800,NaN,1057.881356,NaN,NaN,NaN,NaN,1.669530e+06,260.697501,0.0,53.933640
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
212681,2023,4,rhodium_temple_tx,8063_CT4,32.403056,-97.700556,127.849994,434.906780,148207.758416,885.530543,0.0,15.961697,5.041577e+05,3012.305485,0.0,54.296835
212682,2023,5,rhodium_temple_tx,8063_CT4,32.403056,-97.700556,107.449929,434.906780,123011.617981,717.826816,0.0,13.222776,4.978932e+05,2905.425363,0.0,53.519580
212683,2023,6,rhodium_temple_tx,8063_CT4,32.403056,-97.700556,22.609749,434.906780,34126.161874,199.668619,0.0,3.681138,6.564292e+05,3840.698757,0.0,70.808037
212684,2023,7,rhodium_temple_tx,8063_CT4,32.403056,-97.700556,41.523345,434.906780,55112.871930,323.044338,0.0,5.953296,5.772406e+05,3383.498446,0.0,62.353573
212685,2023,8,rhodium_temple_tx,8063_CT4,32.403056,-97.700556,111.286247,434.906780,157025.484562,919.588070,0.0,16.952629,6.136558e+05,3593.751216,0.0,66.250895

In [23]:
df_complete_peryear_month = df_complete.groupby(['miner','plant_unit','LAT','LON','year','month']).sum().reset_index()

In [24]:
df_complete_peryear_month[df_complete_peryear_month.miner == 'massena_complex_massena_ny'].year.unique()

array([2018, 2019, 2020, 2021, 2022, 2023])

In [25]:
df_complete_2022_2023 = df_complete_peryear_month[((df_complete_peryear_month.year == 2022) & (df_complete_peryear_month.month >= 8)) | ((df_complete_peryear_month.year == 2023) & (df_complete_peryear_month.month <= 7))]
df_complete_2022_2023

,miner,plant_unit,LAT,LON,year,month,marginalMW_wattime,marginalMW_NO_wattime,co2_lbs_wattime,nox_lbs_wattime,so2_lbs_wattime,pm25_lbs_wattime,co2_lbs_NO_wattime,nox_lbs_NO_wattime,so2_lbs_NO_wattime,pm25_lbs_NO_wattime
2,aboutbit_sullivan_county_facility_merom_in,1001_1,39.924200,-87.424400,2022,8,118.600930,89.231377,229720.256329,100.197120,74.638001,26.290358,1.728338e+05,75.384965,56.155138,19.779987
3,aboutbit_sullivan_county_facility_merom_in,1001_1,39.924200,-87.424400,2022,9,71.609597,89.231377,137865.549074,67.783289,81.285903,15.778114,1.717917e+05,84.463486,101.288840,19.660812
4,aboutbit_sullivan_county_facility_merom_in,1001_1,39.924200,-87.424400,2022,10,46.092630,89.231377,89260.509106,145.263218,39.371236,10.215426,1.728007e+05,281.217126,76.219336,19.776188
5,aboutbit_sullivan_county_facility_merom_in,1001_1,39.924200,-87.424400,2022,11,74.906106,89.231377,142641.583504,227.158612,123.081409,16.324729,1.699208e+05,270.601113,146.619871,19.446720
6,aboutbit_sullivan_county_facility_merom_in,1001_1,39.924200,-87.424400,2022,12,88.019919,89.231377,169274.719633,275.365605,59.407847,19.372733,1.716045e+05,279.155586,60.225504,19.639368
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208607,whinstone_us_rockdale_tx,8063_CT4,32.403056,-97.700556,2023,3,259.673786,1057.881356,326290.495201,1967.315118,0.000000,34.889908,1.329270e+06,8014.617169,0.000000,142.137500
208608,whinstone_us_rockdale_tx,8063_CT4,32.403056,-97.700556,2023,4,313.810291,1057.881356,363778.820394,2173.551911,0.000000,39.178294,1.226330e+06,7327.229557,0.000000,132.073384
208609,whinstone_us_rockdale_tx,8063_CT4,32.403056,-97.700556,2023,5,261.364692,1057.881356,299217.449143,1746.065227,0.000000,32.163510,1.211092e+06,7067.250884,0.000000,130.182762
208610,whinstone_us_rockdale_tx,8063_CT4,32.403056,-97.700556,2023,6,54.996688,1057.881356,83009.582936,485.680425,0.000000,8.954120,1.596720e+06,9342.240221,0.000000,172.235766
208611,whinstone_us_rockdale_tx,8063_CT4,32.403056,-97.700556,2023,7,101.002731,1057.881356,134058.337128,785.783525,0.000000,14.480991,1.404099e+06,8230.131356,0.000000,151.670853

In [26]:
df_complete_2022_2023[df_complete_2022_2023.miner == 'massena_complex_massena_ny'].month.unique()

array([ 8,  9, 10, 11, 12,  1,  2,  3,  4,  5,  6,  7])

In [27]:
df_complete_2022_2023_specs = pd.merge(right = df_complete_2022_2023, left = df_unit_rates[df_unit_rates.month==1], on=['plant_unit', 'LAT','LON'])

df_complete_2022_2023_specs.pop('month_x')

0        1
1        1
2        1
3        1
4        1
        ..
97222    1
97223    1
97224    1
97225    1
97226    1
Name: month_x, Length: 97227, dtype: int64

In [28]:
df_complete_2022_2023

,miner,plant_unit,LAT,LON,year,month,marginalMW_wattime,marginalMW_NO_wattime,co2_lbs_wattime,nox_lbs_wattime,so2_lbs_wattime,pm25_lbs_wattime,co2_lbs_NO_wattime,nox_lbs_NO_wattime,so2_lbs_NO_wattime,pm25_lbs_NO_wattime
2,aboutbit_sullivan_county_facility_merom_in,1001_1,39.924200,-87.424400,2022,8,118.600930,89.231377,229720.256329,100.197120,74.638001,26.290358,1.728338e+05,75.384965,56.155138,19.779987
3,aboutbit_sullivan_county_facility_merom_in,1001_1,39.924200,-87.424400,2022,9,71.609597,89.231377,137865.549074,67.783289,81.285903,15.778114,1.717917e+05,84.463486,101.288840,19.660812
4,aboutbit_sullivan_county_facility_merom_in,1001_1,39.924200,-87.424400,2022,10,46.092630,89.231377,89260.509106,145.263218,39.371236,10.215426,1.728007e+05,281.217126,76.219336,19.776188
5,aboutbit_sullivan_county_facility_merom_in,1001_1,39.924200,-87.424400,2022,11,74.906106,89.231377,142641.583504,227.158612,123.081409,16.324729,1.699208e+05,270.601113,146.619871,19.446720
6,aboutbit_sullivan_county_facility_merom_in,1001_1,39.924200,-87.424400,2022,12,88.019919,89.231377,169274.719633,275.365605,59.407847,19.372733,1.716045e+05,279.155586,60.225504,19.639368
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208607,whinstone_us_rockdale_tx,8063_CT4,32.403056,-97.700556,2023,3,259.673786,1057.881356,326290.495201,1967.315118,0.000000,34.889908,1.329270e+06,8014.617169,0.000000,142.137500
208608,whinstone_us_rockdale_tx,8063_CT4,32.403056,-97.700556,2023,4,313.810291,1057.881356,363778.820394,2173.551911,0.000000,39.178294,1.226330e+06,7327.229557,0.000000,132.073384
208609,whinstone_us_rockdale_tx,8063_CT4,32.403056,-97.700556,2023,5,261.364692,1057.881356,299217.449143,1746.065227,0.000000,32.163510,1.211092e+06,7067.250884,0.000000,130.182762
208610,whinstone_us_rockdale_tx,8063_CT4,32.403056,-97.700556,2023,6,54.996688,1057.881356,83009.582936,485.680425,0.000000,8.954120,1.596720e+06,9342.240221,0.000000,172.235766
208611,whinstone_us_rockdale_tx,8063_CT4,32.403056,-97.700556,2023,7,101.002731,1057.881356,134058.337128,785.783525,0.000000,14.480991,1.404099e+06,8230.131356,0.000000,151.670853

In [31]:
df_complete_2022_2023.to_csv('/n/dominici_lab/lab/data/bitcoin_mining_env_burden/intermediate/df_complete_2022_2023.csv')

In [32]:
df_complete_2022_2023.groupby('miner').sum()['marginalMW_wattime'].reset_index().sort_values(by='marginalMW_wattime', ascending =False)

                                                miner  marginalMW_wattime
34                           whinstone_us_rockdale_tx        3.601861e+06
4                            atlas_power_williston_nd        1.684702e+06
7                                    cipher_odessa_tx        1.604249e+06
11                             compute_north_upton_tx        1.416397e+06
6                                 bitdeer_rockdale_tx        1.360703e+06
33                             viking_data_centers_oh        1.237057e+06
16             core_scientific_dalton_green_dalton_ga        1.085096e+06
19                           core_scientific_pecos_tx        1.084999e+06
28                                  rhodium_temple_tx        1.057500e+06
21                                   genesis_pyote_tx        1.046249e+06
12                    core_scientific_calvert_city_ky        9.776080e+05
17                          core_scientific_denton_tx        9.680122e+05
23                         massena_complex_massena_ny        9.638000e+05
27                                   poolin__pecos_tx        7.749994e+05
2                                       argo_afton_tx        7.744097e+05
18  core_scientific_grand_forks_county_facility_gr...        7.565132e+05
1                     applied_blockchain_jamestown_nd        6.959922e+05
10   compute_north_buffalo_county_facility_kearney_ne        6.217704e+05
29                         sangha_systems_hennepin_il        6.215685e+05
9                          cleanspark_sandersville_ga        5.501894e+05
14  core_scientific_cherokee_county_facility_marbl...        4.903985e+05
0          aboutbit_sullivan_county_facility_merom_in        4.320687e+05
15             core_scientific_dalton_brown_dalton_ga        4.050006e+05
5                                bitdeer_knoxville_tn        3.910432e+05
22                    greenidge_generation_dresden_ny        3.661156e+05
31          stronghold_digital_mining_nesquehoning_pa        3.360456e+05
30            stronghold_digital_mining_kennerdell_pa        3.360456e+05
32                  terawulf_lake_mariner_somerset_ny        3.226442e+05
20                              digihost_tonawanda_ny        3.051851e+05
8                          cleanspark_college_park_ga        2.903778e+05
24             mawson_infrastructure_group_midland_pa        2.734546e+05
13  core_scientific_cherokee_county_facility_marbl...        2.281085e+05
26                     merkle_standard_south_carolina        2.125217e+05
3                                atlas_power_butte_mt        2.088514e+05
25  merkle_standard_pend_oreille_county_facility_u...        1.275873e+05

# INMAP pre processing

In [33]:
import geopandas as gpd
import pandas as pd
import os

In [36]:
df_complete_2022_2023 = pd.read_csv('../data/intermediate/df_complete_2022_2023.csv')

In [37]:
df_complete_2022_2023.head()

,Unnamed: 0,miner,plant_unit,LAT,LON,year,month,marginalMW_wattime,marginalMW_NO_wattime,co2_lbs_wattime,nox_lbs_wattime,so2_lbs_wattime,pm25_lbs_wattime,co2_lbs_NO_wattime,nox_lbs_NO_wattime,so2_lbs_NO_wattime,pm25_lbs_NO_wattime
0,2,aboutbit_sullivan_county_facility_merom_in,1001_1,39.9242,-87.4244,2022,8,118.600930,89.231377,229720.256329,100.197120,74.638001,26.290358,172833.845228,75.384965,56.155138,19.779987
1,3,aboutbit_sullivan_county_facility_merom_in,1001_1,39.9242,-87.4244,2022,9,71.609597,89.231377,137865.549074,67.783289,81.285903,15.778114,171791.677378,84.463486,101.288840,19.660812
2,4,aboutbit_sullivan_county_facility_merom_in,1001_1,39.9242,-87.4244,2022,10,46.092630,89.231377,89260.509106,145.263218,39.371236,10.215426,172800.687209,281.217126,76.219336,19.776188
3,5,aboutbit_sullivan_county_facility_merom_in,1001_1,39.9242,-87.4244,2022,11,74.906106,89.231377,142641.583504,227.158612,123.081409,16.324729,169920.792191,270.601113,146.619871,19.446720
4,6,aboutbit_sullivan_county_facility_merom_in,1001_1,39.9242,-87.4244,2022,12,88.019919,89.231377,169274.719633,275.365605,59.407847,19.372733,171604.523732,279.155586,60.225504,19.639368

In [38]:
df_complete_2022_2023.pop('Unnamed: 0')

0             2
1             3
2             4
3             5
4             6
          ...
97250    208607
97251    208608
97252    208609
97253    208610
97254    208611
Name: Unnamed: 0, Length: 97255, dtype: int64

In [39]:
df_complete_2022_2023#.groupby(['LAT','LON']).sum().reset_index()

,miner,plant_unit,LAT,LON,year,month,marginalMW_wattime,marginalMW_NO_wattime,co2_lbs_wattime,nox_lbs_wattime,so2_lbs_wattime,pm25_lbs_wattime,co2_lbs_NO_wattime,nox_lbs_NO_wattime,so2_lbs_NO_wattime,pm25_lbs_NO_wattime
0,aboutbit_sullivan_county_facility_merom_in,1001_1,39.924200,-87.424400,2022,8,118.600930,89.231377,229720.256329,100.197120,74.638001,26.290358,1.728338e+05,75.384965,56.155138,19.779987
1,aboutbit_sullivan_county_facility_merom_in,1001_1,39.924200,-87.424400,2022,9,71.609597,89.231377,137865.549074,67.783289,81.285903,15.778114,1.717917e+05,84.463486,101.288840,19.660812
2,aboutbit_sullivan_county_facility_merom_in,1001_1,39.924200,-87.424400,2022,10,46.092630,89.231377,89260.509106,145.263218,39.371236,10.215426,1.728007e+05,281.217126,76.219336,19.776188
3,aboutbit_sullivan_county_facility_merom_in,1001_1,39.924200,-87.424400,2022,11,74.906106,89.231377,142641.583504,227.158612,123.081409,16.324729,1.699208e+05,270.601113,146.619871,19.446720
4,aboutbit_sullivan_county_facility_merom_in,1001_1,39.924200,-87.424400,2022,12,88.019919,89.231377,169274.719633,275.365605,59.407847,19.372733,1.716045e+05,279.155586,60.225504,19.639368
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97250,whinstone_us_rockdale_tx,8063_CT4,32.403056,-97.700556,2023,3,259.673786,1057.881356,326290.495201,1967.315118,0.000000,34.889908,1.329270e+06,8014.617169,0.000000,142.137500
97251,whinstone_us_rockdale_tx,8063_CT4,32.403056,-97.700556,2023,4,313.810291,1057.881356,363778.820394,2173.551911,0.000000,39.178294,1.226330e+06,7327.229557,0.000000,132.073384
97252,whinstone_us_rockdale_tx,8063_CT4,32.403056,-97.700556,2023,5,261.364692,1057.881356,299217.449143,1746.065227,0.000000,32.163510,1.211092e+06,7067.250884,0.000000,130.182762
97253,whinstone_us_rockdale_tx,8063_CT4,32.403056,-97.700556,2023,6,54.996688,1057.881356,83009.582936,485.680425,0.000000,8.954120,1.596720e+06,9342.240221,0.000000,172.235766
97254,whinstone_us_rockdale_tx,8063_CT4,32.403056,-97.700556,2023,7,101.002731,1057.881356,134058.337128,785.783525,0.000000,14.480991,1.404099e+06,8230.131356,0.000000,151.670853

In [40]:
df_complete_2022_2023_inmap =  df_complete_2022_2023.groupby(['LAT','LON']).sum().reset_index()[['LAT','LON','co2_lbs_wattime','so2_lbs_wattime',
                                                                 'nox_lbs_wattime','pm25_lbs_wattime']]

In [41]:
df_complete_2022_2023_inmap

,LAT,LON,co2_lbs_wattime,so2_lbs_wattime,nox_lbs_wattime,pm25_lbs_wattime
0,25.913100,-97.521400,2.406147e+07,121.496303,6578.630764,1450.711312
1,26.340300,-98.190000,4.052878e+07,204.600672,5158.785462,1395.433978
2,26.341720,-98.175759,4.407154e+07,222.488827,13900.510278,1816.669207
3,27.566700,-99.508900,2.424031e+07,122.384591,2106.857586,681.943322
4,27.606400,-97.311700,1.152199e+08,581.677887,62052.831834,8494.406652
...,...,...,...,...,...,...
651,47.785800,-116.920300,7.410000e+07,374.079950,8028.346327,3563.905637
652,47.796667,-103.578610,3.758167e+06,18.975929,406.128960,101.819127
653,47.804270,-116.867312,4.174450e+07,210.758337,13166.504975,1075.310384
654,48.210000,-104.391667,8.835800e+05,4.461440,665.165134,105.677675
655,48.232500,-103.952780,8.220738e+06,41.509360,1102.407377,571.923964

In [42]:
df_sf = gpd.GeoDataFrame(
    df_complete_2022_2023_inmap,
    geometry=gpd.points_from_xy(df_complete_2022_2023_inmap.LON, df_complete_2022_2023_inmap.LAT),
    crs ='WGS84'
)
#df_sf = df_sf.to_crs({'init':'epsg:2163'})
df_sf = df_sf.to_crs('ESRI:102003')

In [43]:
#lbs to kg
df_sf['co2_kg_wattime'] = df_sf['co2_lbs_wattime'] * 0.453592
df_sf['pm25_kg_wattime'] = df_sf['pm25_lbs_wattime']* 0.453592
df_sf['so2_kg_wattime'] = df_sf['so2_lbs_wattime'] * 0.453592
df_sf['nox_kg_wattime'] = df_sf['nox_lbs_wattime']* 0.453592

In [44]:
df_sf

,LAT,LON,co2_lbs_wattime,so2_lbs_wattime,nox_lbs_wattime,pm25_lbs_wattime,geometry,co2_kg_wattime,pm25_kg_wattime,so2_kg_wattime,nox_kg_wattime
0,25.913100,-97.521400,2.406147e+07,121.496303,6578.630764,1450.711312,POINT (-153851.890 -1287360.227),1.091409e+07,658.031045,55.109751,2984.014285
1,26.340300,-98.190000,4.052878e+07,204.600672,5158.785462,1395.433978,POINT (-220373.783 -1239132.956),1.838353e+07,632.957689,92.805228,2339.983815
2,26.341720,-98.175759,4.407154e+07,222.488827,13900.510278,1816.669207,POINT (-218937.420 -1239009.849),1.999050e+07,824.026619,100.919152,6305.160258
3,27.566700,-99.508900,2.424031e+07,122.384591,2106.857586,681.943322,POINT (-348058.489 -1100217.697),1.099521e+07,309.324035,55.512671,955.653746
4,27.606400,-97.311700,1.152199e+08,581.677887,62052.831834,8494.406652,POINT (-130076.139 -1101367.017),5.226284e+07,3852.994902,263.844436,28146.668097
...,...,...,...,...,...,...,...,...,...,...,...
651,47.785800,-116.920300,7.410000e+07,374.079950,8028.346327,3563.905637,POINT (-1566625.009 1320881.508),3.361117e+07,1616.559086,169.679673,3641.593667
652,47.796667,-103.578610,3.758167e+06,18.975929,406.128960,101.819127,POINT (-571435.160 1171742.166),1.704675e+06,46.184342,8.607330,184.216847
653,47.804270,-116.867312,4.174450e+07,210.758337,13166.504975,1075.310384,POINT (-1562277.071 1321998.441),1.893497e+07,487.752188,95.598296,5972.221325
654,48.210000,-104.391667,8.835800e+05,4.461440,665.165134,105.677675,POINT (-628569.404 1222294.518),4.007848e+05,47.934548,2.023673,301.713584
655,48.232500,-103.952780,8.220738e+06,41.509360,1102.407377,571.923964,POINT (-595566.679 1221937.800),3.728861e+06,259.420135,18.828314,500.043167

In [45]:
in_map_df_sf_22_23 = df_sf[['geometry','pm25_kg_wattime', 'nox_kg_wattime','so2_kg_wattime',]]

In [46]:
in_map_df_sf_22_23

,geometry,pm25_kg_wattime,nox_kg_wattime,so2_kg_wattime
0,POINT (-153851.890 -1287360.227),658.031045,2984.014285,55.109751
1,POINT (-220373.783 -1239132.956),632.957689,2339.983815,92.805228
2,POINT (-218937.420 -1239009.849),824.026619,6305.160258,100.919152
3,POINT (-348058.489 -1100217.697),309.324035,955.653746,55.512671
4,POINT (-130076.139 -1101367.017),3852.994902,28146.668097,263.844436
...,...,...,...,...
651,POINT (-1566625.009 1320881.508),1616.559086,3641.593667,169.679673
652,POINT (-571435.160 1171742.166),46.184342,184.216847,8.607330
653,POINT (-1562277.071 1321998.441),487.752188,5972.221325,95.598296
654,POINT (-628569.404 1222294.518),47.934548,301.713584,2.023673
655,POINT (-595566.679 1221937.800),259.420135,500.043167,18.828314

In [47]:
#VOC, NOx, NH3, SOx, and PM2_5

In [48]:
#in_map_df_sf_2022[['geometry','pm25_kg_NO_wattime','pm25_kg_wattime','so2_kg_wattime']]
#VOC, NOx, NH3, SOx, and PM2_5

NameError: name 'in_map_df_sf_2022' is not defined

In [49]:
in_map_df_sf_22_23 = in_map_df_sf_22_23.rename(columns={'pm25_kg_wattime': 'PM2_5'})
in_map_df_sf_22_23 = in_map_df_sf_22_23.rename(columns={'nox_kg_wattime': 'NOx'})
in_map_df_sf_22_23 = in_map_df_sf_22_23.rename(columns={'so2_kg_wattime': 'SOx'})

In [50]:
in_map_df_sf_22_23 = in_map_df_sf_22_23[['geometry','PM2_5','NOx','SOx']]

In [51]:
in_map_df_sf_22_23

                             geometry        PM2_5           NOx         SOx
0    POINT (-153851.890 -1287360.227)   658.031045   2984.014285   55.109751
1    POINT (-220373.783 -1239132.956)   632.957689   2339.983815   92.805228
2    POINT (-218937.420 -1239009.849)   824.026619   6305.160258  100.919152
3    POINT (-348058.489 -1100217.697)   309.324035    955.653746   55.512671
4    POINT (-130076.139 -1101367.017)  3852.994902  28146.668097  263.844436
..                                ...          ...           ...         ...
651  POINT (-1566625.009 1320881.508)  1616.559086   3641.593667  169.679673
652   POINT (-571435.160 1171742.166)    46.184342    184.216847    8.607330
653  POINT (-1562277.071 1321998.441)   487.752188   5972.221325   95.598296
654   POINT (-628569.404 1222294.518)    47.934548    301.713584    2.023673
655   POINT (-595566.679 1221937.800)   259.420135    500.043167   18.828314

[656 rows x 4 columns]

In [ ]:
#in_map_df_sf_22_23.to_file('/Users/gianlucaguidi/inmap/cmd/inmap/evaldata_v1.6.1/emissions_2022/emissions_2022_2023_complete_CORRECTED.shp')

In [52]:
in_map_df_sf_22_23.to_file('/n/dominici_lab/lab/data/bitcoin_mining_env_burden/intermediate/emissions_2022_2023.shp')